######################## default configuration ####################
baseURL = "/"
languageCode = "en"
title = "Vancroft" 
theme = "hargo"
timeZone = "America/New_York"
pagination.pagerSize = 10
summaryLength = 20
disableLanguages = []
hasCJKLanguage = false
timeout = "500s"

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
[params.plugins]
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
# YOUR CUSTOM LUXURY CSS
[[params.plugins.css]]
link = "css/laxury.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
# BRANDING UPDATED HERE
logo = "images/vancroft-logo.jpg"
home = "Home"
description = "Vancroft - Luxury 3D Printed Goods"
author = "Vancroft"

# Map & Contact (You can update these later)
gmapAPI = ""
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
mobile = ""
email = "info@vancroft.com"
location = "Greece"
copyright = "| Copyright &copy; 2026 Vancroft |"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "â‚¬"

[params.preloader]
enable = true
preloader = ""

[params.rating]
enable = false
websiteID = "444334"
publicKey = "811cf0927332bf51f2e12f84608594ac"

[[params.social]]
icon = "ti-instagram"
link = "#"

[params.contact]
formAction = "#"