############################## navigation ##############################
[[main]]
name = "Products" # ΑΛΛΑΓΗ: Αντί για Products
URL = "products/"
weight = 1

[[main]]
name = "Journal"    # ΑΛΛΑΓΗ: Αντί για Blog
URL = "blog/"       # Προσοχή: Το URL μένει "blog/" για να μη σπάσει η δομή των φακέλων
weight = 2

[[main]]
name = "Philosophy" # ΑΛΛΑΓΗ: Αντί για FAQ ή About (πιο ταιριαστό)
URL = "about/"      # Θα πρέπει να φτιάξουμε και μια σελίδα about αν δεν υπάρχει
weight = 3

[[main]]
name = "Contact"
URL = "contact/"
weight = 4

############# footer menu #############
[[footer]]
name = "Products"
URL = "products/"
weight = 1

[[footer]]
name = "Journal"
URL = "blog/"
weight = 2

[[footer]]
name = "Contact"
URL = "contact/"
weight = 5